/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routesTanstack/__root'
import { Route as RegisterRouteImport } from './routesTanstack/register'
import { Route as LoginRouteImport } from './routesTanstack/login'
import { Route as AcceptRouteImport } from './routesTanstack/accept'
import { Route as AuthenticatedRouteImport } from './routesTanstack/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routesTanstack/_authenticated/index'
import { Route as AuthenticatedWorkspaceRouteImport } from './routesTanstack/_authenticated/workspace'
import { Route as AuthenticatedWorkspaceWorkspace_idRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id'
import { Route as AuthenticatedWorkspaceWorkspace_idIndexRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/index'
import { Route as AuthenticatedWorkspaceWorkspace_idTaskTodoRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/taskTodo'
import { Route as AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/workspaceSettings/index'
import { Route as AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/taskTodo/index'
import { Route as AuthenticatedWorkspaceWorkspace_idProjectIndexRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/project/index'
import { Route as AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/project/$project_id/index'
import { Route as AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/project/$project_id/taskboard'
import { Route as AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/project/$project_id/projectSettings/index'
import { Route as AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id'
import { Route as AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRouteImport } from './routesTanstack/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptRoute = AcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceWorkspace_idRoute =
  AuthenticatedWorkspaceWorkspace_idRouteImport.update({
    id: '/$workspace_id',
    path: '/$workspace_id',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceWorkspace_idIndexRoute =
  AuthenticatedWorkspaceWorkspace_idIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspace_idRoute,
  } as any)
const AuthenticatedWorkspaceWorkspace_idTaskTodoRoute =
  AuthenticatedWorkspaceWorkspace_idTaskTodoRouteImport.update({
    id: '/taskTodo',
    path: '/taskTodo',
    getParentRoute: () => AuthenticatedWorkspaceWorkspace_idRoute,
  } as any)
const AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute =
  AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRouteImport.update({
    id: '/workspaceSettings/',
    path: '/workspaceSettings/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspace_idRoute,
  } as any)
const AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute =
  AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspace_idTaskTodoRoute,
  } as any)
const AuthenticatedWorkspaceWorkspace_idProjectIndexRoute =
  AuthenticatedWorkspaceWorkspace_idProjectIndexRouteImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspace_idRoute,
  } as any)
const AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute =
  AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRouteImport.update({
    id: '/project/$project_id/',
    path: '/project/$project_id/',
    getParentRoute: () => AuthenticatedWorkspaceWorkspace_idRoute,
  } as any)
const AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRoute =
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteImport.update(
    {
      id: '/project/$project_id/taskboard',
      path: '/project/$project_id/taskboard',
      getParentRoute: () => AuthenticatedWorkspaceWorkspace_idRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute =
  AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRouteImport.update(
    {
      id: '/project/$project_id/projectSettings/',
      path: '/project/$project_id/projectSettings/',
      getParentRoute: () => AuthenticatedWorkspaceWorkspace_idRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRoute =
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteImport.update(
    {
      id: '/$taskboard_id',
      path: '/$taskboard_id',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRoute,
    } as any,
  )
const AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute =
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRouteImport.update(
    {
      id: '/$task_id',
      path: '/$task_id',
      getParentRoute: () =>
        AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/workspace/$workspace_id': typeof AuthenticatedWorkspaceWorkspace_idRouteWithChildren
  '/workspace/$workspace_id/taskTodo': typeof AuthenticatedWorkspaceWorkspace_idTaskTodoRouteWithChildren
  '/workspace/$workspace_id/': typeof AuthenticatedWorkspaceWorkspace_idIndexRoute
  '/workspace/$workspace_id/project/': typeof AuthenticatedWorkspaceWorkspace_idProjectIndexRoute
  '/workspace/$workspace_id/taskTodo/': typeof AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute
  '/workspace/$workspace_id/workspaceSettings/': typeof AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute
  '/workspace/$workspace_id/project/$project_id/taskboard': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteWithChildren
  '/workspace/$workspace_id/project/$project_id/': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute
  '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteWithChildren
  '/workspace/$workspace_id/project/$project_id/projectSettings/': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute
  '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute
}
export interface FileRoutesByTo {
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/workspace/$workspace_id': typeof AuthenticatedWorkspaceWorkspace_idIndexRoute
  '/workspace/$workspace_id/project': typeof AuthenticatedWorkspaceWorkspace_idProjectIndexRoute
  '/workspace/$workspace_id/taskTodo': typeof AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute
  '/workspace/$workspace_id/workspaceSettings': typeof AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute
  '/workspace/$workspace_id/project/$project_id/taskboard': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteWithChildren
  '/workspace/$workspace_id/project/$project_id': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute
  '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteWithChildren
  '/workspace/$workspace_id/project/$project_id/projectSettings': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute
  '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept': typeof AcceptRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/workspace/$workspace_id': typeof AuthenticatedWorkspaceWorkspace_idRouteWithChildren
  '/_authenticated/workspace/$workspace_id/taskTodo': typeof AuthenticatedWorkspaceWorkspace_idTaskTodoRouteWithChildren
  '/_authenticated/workspace/$workspace_id/': typeof AuthenticatedWorkspaceWorkspace_idIndexRoute
  '/_authenticated/workspace/$workspace_id/project/': typeof AuthenticatedWorkspaceWorkspace_idProjectIndexRoute
  '/_authenticated/workspace/$workspace_id/taskTodo/': typeof AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute
  '/_authenticated/workspace/$workspace_id/workspaceSettings/': typeof AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute
  '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteWithChildren
  '/_authenticated/workspace/$workspace_id/project/$project_id/': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute
  '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteWithChildren
  '/_authenticated/workspace/$workspace_id/project/$project_id/projectSettings/': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute
  '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id': typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept'
    | '/login'
    | '/register'
    | '/workspace'
    | '/workspace/$workspace_id'
    | '/workspace/$workspace_id/taskTodo'
    | '/workspace/$workspace_id/'
    | '/workspace/$workspace_id/project/'
    | '/workspace/$workspace_id/taskTodo/'
    | '/workspace/$workspace_id/workspaceSettings/'
    | '/workspace/$workspace_id/project/$project_id/taskboard'
    | '/workspace/$workspace_id/project/$project_id/'
    | '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id'
    | '/workspace/$workspace_id/project/$project_id/projectSettings/'
    | '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept'
    | '/login'
    | '/register'
    | '/workspace'
    | '/'
    | '/workspace/$workspace_id'
    | '/workspace/$workspace_id/project'
    | '/workspace/$workspace_id/taskTodo'
    | '/workspace/$workspace_id/workspaceSettings'
    | '/workspace/$workspace_id/project/$project_id/taskboard'
    | '/workspace/$workspace_id/project/$project_id'
    | '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id'
    | '/workspace/$workspace_id/project/$project_id/projectSettings'
    | '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept'
    | '/login'
    | '/register'
    | '/_authenticated/workspace'
    | '/_authenticated/'
    | '/_authenticated/workspace/$workspace_id'
    | '/_authenticated/workspace/$workspace_id/taskTodo'
    | '/_authenticated/workspace/$workspace_id/'
    | '/_authenticated/workspace/$workspace_id/project/'
    | '/_authenticated/workspace/$workspace_id/taskTodo/'
    | '/_authenticated/workspace/$workspace_id/workspaceSettings/'
    | '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard'
    | '/_authenticated/workspace/$workspace_id/project/$project_id/'
    | '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id'
    | '/_authenticated/workspace/$workspace_id/project/$project_id/projectSettings/'
    | '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptRoute: typeof AcceptRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept': {
      id: '/accept'
      path: '/accept'
      fullPath: '/accept'
      preLoaderRoute: typeof AcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/$workspace_id': {
      id: '/_authenticated/workspace/$workspace_id'
      path: '/$workspace_id'
      fullPath: '/workspace/$workspace_id'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/$workspace_id/': {
      id: '/_authenticated/workspace/$workspace_id/'
      path: '/'
      fullPath: '/workspace/$workspace_id/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idRoute
    }
    '/_authenticated/workspace/$workspace_id/taskTodo': {
      id: '/_authenticated/workspace/$workspace_id/taskTodo'
      path: '/taskTodo'
      fullPath: '/workspace/$workspace_id/taskTodo'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idTaskTodoRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idRoute
    }
    '/_authenticated/workspace/$workspace_id/workspaceSettings/': {
      id: '/_authenticated/workspace/$workspace_id/workspaceSettings/'
      path: '/workspaceSettings'
      fullPath: '/workspace/$workspace_id/workspaceSettings/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idRoute
    }
    '/_authenticated/workspace/$workspace_id/taskTodo/': {
      id: '/_authenticated/workspace/$workspace_id/taskTodo/'
      path: '/'
      fullPath: '/workspace/$workspace_id/taskTodo/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idTaskTodoRoute
    }
    '/_authenticated/workspace/$workspace_id/project/': {
      id: '/_authenticated/workspace/$workspace_id/project/'
      path: '/project'
      fullPath: '/workspace/$workspace_id/project/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idRoute
    }
    '/_authenticated/workspace/$workspace_id/project/$project_id/': {
      id: '/_authenticated/workspace/$workspace_id/project/$project_id/'
      path: '/project/$project_id'
      fullPath: '/workspace/$workspace_id/project/$project_id/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idRoute
    }
    '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard': {
      id: '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard'
      path: '/project/$project_id/taskboard'
      fullPath: '/workspace/$workspace_id/project/$project_id/taskboard'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idRoute
    }
    '/_authenticated/workspace/$workspace_id/project/$project_id/projectSettings/': {
      id: '/_authenticated/workspace/$workspace_id/project/$project_id/projectSettings/'
      path: '/project/$project_id/projectSettings'
      fullPath: '/workspace/$workspace_id/project/$project_id/projectSettings/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idRoute
    }
    '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id': {
      id: '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id'
      path: '/$taskboard_id'
      fullPath: '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRoute
    }
    '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id': {
      id: '/_authenticated/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id'
      path: '/$task_id'
      fullPath: '/workspace/$workspace_id/project/$project_id/taskboard/$taskboard_id/$task_id'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRouteImport
      parentRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRoute
    }
  }
}

interface AuthenticatedWorkspaceWorkspace_idTaskTodoRouteChildren {
  AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute: typeof AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute
}

const AuthenticatedWorkspaceWorkspace_idTaskTodoRouteChildren: AuthenticatedWorkspaceWorkspace_idTaskTodoRouteChildren =
  {
    AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute:
      AuthenticatedWorkspaceWorkspace_idTaskTodoIndexRoute,
  }

const AuthenticatedWorkspaceWorkspace_idTaskTodoRouteWithChildren =
  AuthenticatedWorkspaceWorkspace_idTaskTodoRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspace_idTaskTodoRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteChildren {
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute
}

const AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteChildren: AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteChildren =
  {
    AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute:
      AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idTask_idRoute,
  }

const AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteWithChildren =
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteChildren {
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteWithChildren
}

const AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteChildren: AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteChildren =
  {
    AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRoute:
      AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardTaskboard_idRouteWithChildren,
  }

const AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteWithChildren =
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteChildren,
  )

interface AuthenticatedWorkspaceWorkspace_idRouteChildren {
  AuthenticatedWorkspaceWorkspace_idTaskTodoRoute: typeof AuthenticatedWorkspaceWorkspace_idTaskTodoRouteWithChildren
  AuthenticatedWorkspaceWorkspace_idIndexRoute: typeof AuthenticatedWorkspaceWorkspace_idIndexRoute
  AuthenticatedWorkspaceWorkspace_idProjectIndexRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectIndexRoute
  AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute: typeof AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute
  AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteWithChildren
  AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute
  AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute: typeof AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute
}

const AuthenticatedWorkspaceWorkspace_idRouteChildren: AuthenticatedWorkspaceWorkspace_idRouteChildren =
  {
    AuthenticatedWorkspaceWorkspace_idTaskTodoRoute:
      AuthenticatedWorkspaceWorkspace_idTaskTodoRouteWithChildren,
    AuthenticatedWorkspaceWorkspace_idIndexRoute:
      AuthenticatedWorkspaceWorkspace_idIndexRoute,
    AuthenticatedWorkspaceWorkspace_idProjectIndexRoute:
      AuthenticatedWorkspaceWorkspace_idProjectIndexRoute,
    AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute:
      AuthenticatedWorkspaceWorkspace_idWorkspaceSettingsIndexRoute,
    AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRoute:
      AuthenticatedWorkspaceWorkspace_idProjectProject_idTaskboardRouteWithChildren,
    AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute:
      AuthenticatedWorkspaceWorkspace_idProjectProject_idIndexRoute,
    AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute:
      AuthenticatedWorkspaceWorkspace_idProjectProject_idProjectSettingsIndexRoute,
  }

const AuthenticatedWorkspaceWorkspace_idRouteWithChildren =
  AuthenticatedWorkspaceWorkspace_idRoute._addFileChildren(
    AuthenticatedWorkspaceWorkspace_idRouteChildren,
  )

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceWorkspace_idRoute: typeof AuthenticatedWorkspaceWorkspace_idRouteWithChildren
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceWorkspace_idRoute:
      AuthenticatedWorkspaceWorkspace_idRouteWithChildren,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptRoute: AcceptRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
