/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthFlowState {
  auth_code: string;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string;
  code_challenge_method: AuthCodeChallengeMethod;
  created_at: Timestamp | null;
  id: string;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  refreshed_at: Timestamp | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface Project {
  created_at: Generated<Timestamp | null>;
  project_id: Generated<string>;
  project_name: string;
}

export interface ProjectBase64 {
  created_at: Timestamp | null;
  project_id: string | null;
  project_name: string | null;
}

export interface ProjectMembers {
  invited_by: string;
  is_active: Generated<boolean | null>;
  joined_at: Generated<Timestamp | null>;
  project_id: string;
  project_role: number;
  user_id: string;
}

export interface ProjectMembersBase64 {
  invited_by: string | null;
  is_active: boolean | null;
  joined_at: Timestamp | null;
  project_id: string | null;
  project_role: number | null;
  user_id: string | null;
}

export interface ProjectRole {
  id: Generated<number>;
  role_name: string;
}

export interface ProjectTags {
  project_id: string;
  tag_color: string;
  tag_id: Generated<string>;
  tag_name: string;
}

export interface ProjectTagsBase64 {
  project_id: string | null;
  tag_color: string | null;
  tag_id: string | null;
  tag_name: string | null;
}

export interface RealtimeMessages {
  event: string | null;
  extension: string;
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  claims: Json;
  claims_role: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  subscription_id: string;
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null;
  avif_autodetection: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  file_size_limit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  public: Generated<boolean | null>;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucket_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  last_accessed_at: Generated<Timestamp | null>;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  path_tokens: Generated<string[] | null>;
  updated_at: Generated<Timestamp | null>;
  user_metadata: Json | null;
  version: string | null;
}

export interface StorageS3MultipartUploads {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  in_progress_size: Generated<Int8>;
  key: string;
  owner_id: string | null;
  upload_signature: string;
  user_metadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  owner_id: string | null;
  part_number: number;
  size: Generated<Int8>;
  upload_id: string;
  version: string;
}

export interface Task {
  created_at: Generated<Timestamp | null>;
  created_by: string;
  display_order: number;
  in_trash: Generated<boolean | null>;
  last_modified: Generated<Timestamp | null>;
  task_deadline: string | null;
  task_description: string | null;
  task_estimate: number | null;
  task_id: Generated<string>;
  task_section_id: string;
  task_title: string;
}

export interface TaskAssignee {
  task_id: string;
  user_id: string;
}

export interface TaskAssigneeBase64 {
  task_id: string | null;
  user_id: string | null;
}

export interface TaskBase64 {
  created_at: Timestamp | null;
  created_by: string | null;
  display_order: number | null;
  in_trash: boolean | null;
  last_modified: Timestamp | null;
  task_deadline: string | null;
  task_description: string | null;
  task_estimate: number | null;
  task_id: string | null;
  task_section_id: string | null;
  task_title: string | null;
}

export interface TaskBoard {
  created_at: Generated<Timestamp | null>;
  project_id: string;
  task_board_id: Generated<string>;
  task_board_name: string | null;
}

export interface TaskBoardBase64 {
  created_at: Timestamp | null;
  project_id: string | null;
  task_board_id: string | null;
  task_board_name: string | null;
}

export interface TaskSection {
  created_at: Generated<Timestamp | null>;
  display_order: number;
  task_board_id: string;
  task_section_id: Generated<string>;
  task_section_name: string;
}

export interface TaskSectionBase64 {
  created_at: Timestamp | null;
  display_order: number | null;
  task_board_id: string | null;
  task_section_id: string | null;
  task_section_name: string | null;
}

export interface TaskTimeLog {
  created_at: Generated<Timestamp | null>;
  task_id: string;
  time_spent: number;
  user_id: string;
}

export interface TaskTimeLogBase64 {
  created_at: Timestamp | null;
  task_id: string | null;
  time_spent: number | null;
  user_id: string | null;
}

export interface User {
  created_at: Generated<Timestamp | null>;
  email: string;
  firstname: string;
  google_user_id: string | null;
  last_modified: Timestamp | null;
  lastname: string;
  password_hashed: string | null;
  user_id: Generated<string>;
}

export interface UserBase64 {
  created_at: Timestamp | null;
  email: string | null;
  firstname: string | null;
  google_user_id: string | null;
  last_modified: Timestamp | null;
  lastname: string | null;
  password_hashed: string | null;
  user_id: string | null;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface Workspace {
  workspace_id: Generated<string>;
  workspace_name: string;
}

export interface WorkspaceBase64 {
  workspace_id: string | null;
  workspace_name: string | null;
}

export interface WorkspaceInvitation {
  accepted: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  email: string;
  sender_id: string;
  token_string: string;
  workspace_id: string;
}

export interface WorkspaceInvitationBase64 {
  accepted: boolean | null;
  created_at: Timestamp | null;
  email: string | null;
  sender_id: string | null;
  token_string: string | null;
  workspace_id: string | null;
}

export interface WorkspaceMembers {
  invited_by: string;
  joined_at: Generated<Timestamp | null>;
  user_id: string;
  workspace_id: string;
  workspace_role: number;
}

export interface WorkspaceMembersBase64 {
  invited_by: string | null;
  joined_at: Timestamp | null;
  user_id: string | null;
  workspace_id: string | null;
  workspace_role: number | null;
}

export interface WorkspaceProjects {
  project_id: string;
  user_id: string;
  workspace_id: string;
}

export interface WorkspaceProjectsBase64 {
  project_id: string | null;
  user_id: string | null;
  workspace_id: string | null;
}

export interface WorkspaceRole {
  id: Generated<number>;
  role_name: string;
}

export interface DB {
  "auth.audit_log_entries": AuthAuditLogEntries;
  "auth.flow_state": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfa_amr_claims": AuthMfaAmrClaims;
  "auth.mfa_challenges": AuthMfaChallenges;
  "auth.mfa_factors": AuthMfaFactors;
  "auth.one_time_tokens": AuthOneTimeTokens;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.saml_providers": AuthSamlProviders;
  "auth.saml_relay_states": AuthSamlRelayStates;
  "auth.schema_migrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.sso_domains": AuthSsoDomains;
  "auth.sso_providers": AuthSsoProviders;
  "auth.users": AuthUsers;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  project: Project;
  project_base64: ProjectBase64;
  project_members: ProjectMembers;
  project_members_base64: ProjectMembersBase64;
  project_role: ProjectRole;
  project_tags: ProjectTags;
  project_tags_base64: ProjectTagsBase64;
  "realtime.messages": RealtimeMessages;
  "realtime.schema_migrations": RealtimeSchemaMigrations;
  "realtime.subscription": RealtimeSubscription;
  "storage.buckets": StorageBuckets;
  "storage.migrations": StorageMigrations;
  "storage.objects": StorageObjects;
  "storage.s3_multipart_uploads": StorageS3MultipartUploads;
  "storage.s3_multipart_uploads_parts": StorageS3MultipartUploadsParts;
  task: Task;
  task_assignee: TaskAssignee;
  task_assignee_base64: TaskAssigneeBase64;
  task_base64: TaskBase64;
  task_board: TaskBoard;
  task_board_base64: TaskBoardBase64;
  task_section: TaskSection;
  task_section_base64: TaskSectionBase64;
  task_time_log: TaskTimeLog;
  task_time_log_base64: TaskTimeLogBase64;
  user: User;
  user_base64: UserBase64;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
  workspace: Workspace;
  workspace_base64: WorkspaceBase64;
  workspace_invitation: WorkspaceInvitation;
  workspace_invitation_base64: WorkspaceInvitationBase64;
  workspace_members: WorkspaceMembers;
  workspace_members_base64: WorkspaceMembersBase64;
  workspace_projects: WorkspaceProjects;
  workspace_projects_base64: WorkspaceProjectsBase64;
  workspace_role: WorkspaceRole;
}
