import { EWorkspaceRole } from "./types/workspace/enums";
import { EProjectRole } from "./types/project/enums";

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export interface InvitationWorkspaceInvitation {
  accepted: Generated<boolean | null>;
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  email: string;
  sender_id: string;
  token_string: string;
  workspace_id: string;
}

export interface InvitationWorkspaceInvitationBase64 {
  accepted: boolean | null;
  created_at: ColumnType<string, string | string, Date | string> | null;
  email: string | null;
  sender_id: string | null;
  token_string: string | null;
  workspace_id: string | null;
}

export interface ProjectProject {
  active: Generated<boolean | null>;
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  created_by: string;
  project_abbreviation: Generated<string>;
  project_color: Generated<string>;
  project_id: Generated<string>;
  project_name: string;
  workspace_id: string;
}

export interface ProjectProjectBase64 {
  active: boolean | null;
  created_at: ColumnType<string, string | string, Date | string> | null;
  created_by: string | null;
  project_abbreviation: string | null;
  project_color: string | null;
  project_id: string | null;
  project_name: string | null;
  workspace_id: string | null;
}

export interface ProjectProjectMembers {
  invited_by: string;
  is_active: Generated<boolean | null>;
  joined_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  project_id: string;
  project_role: EProjectRole;
  user_id: string;
}

export interface ProjectProjectMembersBase64 {
  invited_by: string | null;
  is_active: boolean | null;
  joined_at: ColumnType<string, string | string, Date | string> | null;
  project_id: string | null;
  project_role: EProjectRole | null;
  user_id: string | null;
}

export interface ProjectProjectRole {
  id: Generated<number>;
  role_name: string;
}

export interface ProjectProjectTags {
  project_id: string;
  tag_color: string;
  tag_id: Generated<string>;
  tag_name: string;
}

export interface ProjectProjectTagsBase64 {
  project_id: string | null;
  tag_color: string | null;
  tag_id: string | null;
  tag_name: string | null;
}

export interface TaskboardTask {
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  created_by: string;
  display_order: number;
  in_trash: Generated<boolean | null>;
  last_modified: Generated<ColumnType<string, string | string, Date | string> | null>;
  task_board_id: string | null;
  task_deadline: string | null;
  task_depth: Generated<number>;
  task_description: string | null;
  task_estimate: number | null;
  task_id: Generated<string>;
  task_section_id: string;
  task_title: string;
}

export interface TaskboardTaskAssignee {
  task_id: string;
  user_id: string;
}

export interface TaskboardTaskAssigneeBase64 {
  task_id: string | null;
  user_id: string | null;
}

export interface TaskboardTaskBase64 {
  created_at: ColumnType<string, string | string, Date | string> | null;
  created_by: string | null;
  display_order: number | null;
  in_trash: boolean | null;
  last_modified: ColumnType<string, string | string, Date | string> | null;
  task_board_id: string | null;
  task_deadline: string | null;
  task_description: string | null;
  task_estimate: number | null;
  task_id: string | null;
  task_section_id: string | null;
  task_title: string | null;
}

export interface TaskboardTaskBoard {
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  inactive: Generated<boolean | null>;
  project_id: string;
  task_board_id: Generated<string>;
  task_board_name: string | null;
}

export interface TaskboardTaskBoardBase64 {
  created_at: ColumnType<string, string | string, Date | string> | null;
  project_id: string | null;
  task_board_id: string | null;
  task_board_name: string | null;
}

export interface TaskboardTaskComment {
  comment_content: string | null;
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  edited_at: ColumnType<string, string | string, Date | string> | null;
  replying_to_task_comment_id: string | null;
  task_comment_id: Generated<string>;
  task_id: string;
  user_id: string;
}

export interface TaskboardTaskSection {
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  display_order: number;
  task_board_id: string;
  task_section_color: string | null;
  task_section_id: Generated<string>;
  task_section_name: string;
}

export interface TaskboardTaskSectionBase64 {
  created_at: ColumnType<string, string | string, Date | string> | null;
  display_order: number | null;
  task_board_id: string | null;
  task_section_color: string | null;
  task_section_id: string | null;
  task_section_name: string | null;
}

export interface TaskboardTaskTag {
  tag_id: string;
  task_id: string;
}

export interface TaskboardTaskTagBase64 {
  tag_id: string | null;
  task_id: string | null;
}

export interface TaskboardTaskTimeLog {
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  task_id: string;
  task_time_log_id: Generated<string>;
  time_spent: number;
  user_id: string;
}

export interface TaskboardTaskTimeLogBase64 {
  created_at: ColumnType<string, string | string, Date | string> | null;
  task_id: string | null;
  task_time_log_id: string | null;
  time_spent: number | null;
  user_id: string | null;
}

export interface TaskboardTaskTodoSessionHistory {
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  task_todo_session_history_id: Generated<string>;
  user_id: string;
  workspace_id: string;
}

export interface TaskboardTaskTodoState {
  active: Generated<boolean | null>;
  current_work_time: Generated<Int8>;
  display_order: number;
  session_started_at: ColumnType<string, string | string, Date | string> | null;
  task_id: string;
  user_id: string;
  work_time_goal: Generated<Int8>;
}

export interface TaskboardTaskTodoStateBase64 {
  active: boolean | null;
  current_work_time: Int8 | null;
  display_order: number | null;
  session_started_at: ColumnType<string, string | string, Date | string> | null;
  task_id: string | null;
  user_id: string | null;
  work_time_goal: Int8 | null;
}

export interface TaskboardTaskTodoStateSnapshot {
  project_abbreviation: string;
  project_color: string;
  project_id: string | null;
  project_name: string;
  task_depth: number;
  task_id: string | null;
  task_title: string;
  task_todo_session_history_id: string;
  task_todo_state_snapshot_id: Generated<string>;
  user_id: string;
  work_time_goal: Int8;
}

export interface TaskboardTaskTodoStateSnapshotTimer {
  last_seen: Generated<ColumnType<string, string | string, Date | string> | null>;
  start: ColumnType<string, string | string, Date | string>;
  stop: ColumnType<string, string | string, Date | string>;
  task_time_log_id: string | null;
  task_todo_state_snapshot_id: string;
  user_id: string;
  workspace_id: string;
}

export interface TaskboardTaskTodoTimer {
  last_seen: Generated<ColumnType<string, string | string, Date | string> | null>;
  start: Generated<ColumnType<string, string | string, Date | string>>;
  stop: ColumnType<string, string | string, Date | string> | null;
  task_id: string;
  task_time_log_id: string | null;
  user_id: string;
  workspace_id: string;
}

export interface TpUserUser {
  created_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  email: string;
  firstname: string;
  google_user_id: string | null;
  last_modified: ColumnType<string, string | string, Date | string> | null;
  lastname: string;
  password_hashed: string | null;
  user_id: Generated<string>;
}

export interface TpUserUserBase64 {
  created_at: ColumnType<string, string | string, Date | string> | null;
  email: string | null;
  firstname: string | null;
  google_user_id: string | null;
  last_modified: ColumnType<string, string | string, Date | string> | null;
  lastname: string | null;
  password_hashed: string | null;
  user_id: string | null;
}

export interface TpUserUserProfilePhoto {
  crop_height: number;
  crop_width: number;
  crop_x: number;
  crop_y: number;
  image_type: string;
  last_modified: Generated<ColumnType<string, string | string, Date | string> | null>;
  photo_file_name: string;
  user_id: string;
}

export interface TpUserUserProfilePhotoBase64 {
  crop_height: number | null;
  crop_width: number | null;
  crop_x: number | null;
  crop_y: number | null;
  image_type: string | null;
  photo_file_name: string | null;
  user_id: string | null;
}

export interface TpUserUserSecure {
  created_at: ColumnType<string, string | string, Date | string> | null;
  email: string | null;
  firstname: string | null;
  last_modified: ColumnType<string, string | string, Date | string> | null;
  lastname: string | null;
  user_id: string | null;
}

export interface TpUserUserSecureBase64 {
  created_at: ColumnType<string, string | string, Date | string> | null;
  email: string | null;
  firstname: string | null;
  last_modified: ColumnType<string, string | string, Date | string> | null;
  lastname: string | null;
  user_id: string | null;
}

export interface WorkspaceWorkspace {
  workspace_id: Generated<string>;
  workspace_name: string;
}

export interface WorkspaceWorkspaceBase64 {
  workspace_id: string | null;
  workspace_name: string | null;
}

export interface WorkspaceWorkspaceMembers {
  invited_by: string;
  joined_at: Generated<ColumnType<string, string | string, Date | string> | null>;
  user_id: string;
  workspace_id: string;
  workspace_role: EWorkspaceRole;
}

export interface WorkspaceWorkspaceMembersBase64 {
  invited_by: string | null;
  joined_at: ColumnType<string, string | string, Date | string> | null;
  user_id: string | null;
  workspace_id: string | null;
  workspace_role: EWorkspaceRole | null;
}

export interface WorkspaceWorkspaceRole {
  id: Generated<number>;
  role_name: string;
}

export interface DB {
  "invitation.workspace_invitation": InvitationWorkspaceInvitation;
  "invitation.workspace_invitation_base64": InvitationWorkspaceInvitationBase64;
  "project.project": ProjectProject;
  "project.project_base64": ProjectProjectBase64;
  "project.project_members": ProjectProjectMembers;
  "project.project_members_base64": ProjectProjectMembersBase64;
  "project.project_role": ProjectProjectRole;
  "project.project_tags": ProjectProjectTags;
  "project.project_tags_base64": ProjectProjectTagsBase64;
  "taskboard.task": TaskboardTask;
  "taskboard.task_assignee": TaskboardTaskAssignee;
  "taskboard.task_assignee_base64": TaskboardTaskAssigneeBase64;
  "taskboard.task_base64": TaskboardTaskBase64;
  "taskboard.task_board": TaskboardTaskBoard;
  "taskboard.task_board_base64": TaskboardTaskBoardBase64;
  "taskboard.task_comment": TaskboardTaskComment;
  "taskboard.task_section": TaskboardTaskSection;
  "taskboard.task_section_base64": TaskboardTaskSectionBase64;
  "taskboard.task_tag": TaskboardTaskTag;
  "taskboard.task_tag_base64": TaskboardTaskTagBase64;
  "taskboard.task_time_log": TaskboardTaskTimeLog;
  "taskboard.task_time_log_base64": TaskboardTaskTimeLogBase64;
  "taskboard.task_todo_session_history": TaskboardTaskTodoSessionHistory;
  "taskboard.task_todo_state": TaskboardTaskTodoState;
  "taskboard.task_todo_state_base64": TaskboardTaskTodoStateBase64;
  "taskboard.task_todo_state_snapshot": TaskboardTaskTodoStateSnapshot;
  "taskboard.task_todo_state_snapshot_timer": TaskboardTaskTodoStateSnapshotTimer;
  "taskboard.task_todo_timer": TaskboardTaskTodoTimer;
  "tp_user.user": TpUserUser;
  "tp_user.user_base64": TpUserUserBase64;
  "tp_user.user_profile_photo": TpUserUserProfilePhoto;
  "tp_user.user_profile_photo_base64": TpUserUserProfilePhotoBase64;
  "tp_user.user_secure": TpUserUserSecure;
  "tp_user.user_secure_base64": TpUserUserSecureBase64;
  "workspace.workspace": WorkspaceWorkspace;
  "workspace.workspace_base64": WorkspaceWorkspaceBase64;
  "workspace.workspace_members": WorkspaceWorkspaceMembers;
  "workspace.workspace_members_base64": WorkspaceWorkspaceMembersBase64;
  "workspace.workspace_role": WorkspaceWorkspaceRole;
}
